name = "Hashpipe"
uuid = "89861ec2-aa86-43f2-b769-fb502ce05d7b"
authors = ["Max Hawkins"]
version = "0.2.1"

[deps]
Hashpipe_jll = "a3e50fc0-e135-5cb8-92f4-a3765d91b533"

[compat]
Hashpipe_jll = "^0.0.2"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
